name: Test
on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Pass a test name'     
        required: true
        default: 'No name provided'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Name: ${{ github.event.inputs.test }}"